version: '3'
services:
  # generate c files by sababi
  sababi: # 容器名为sababi
    build: ./sa_babi # 基于./sa_babi目录下的docker-file创建镜像
    volumes:
      - "${DATA_DIR}:/mnt/data" # 将${DATA_DIR}目录挂载到镜像的/mnt/data目录下

